#!/usr/bin/env swift
import Foundation

// Parses Tools/emoji-test.txt (Unicode UTS #51) into a categorized
// Swift catalog under Heidrun/Icons/Generated/:
//
//   Emojis.generated.swift        — enum + struct + `all` index
//   Emojis.<Group>.generated.swift — per-group `static let` extensions,
//                                    chunked to stay under SwiftLint's
//                                    file_length / type_body_length caps
//
// Regenerate after a Unicode emoji bump:
//
//   curl -sSL https://unicode.org/Public/emoji/latest/emoji-test.txt > Tools/emoji-test.txt
//   swift Tools/GenerateEmojis.swift
//
// Must be run from the repo root (paths are repo-relative).

let inputPath = "Tools/emoji-test.txt"
let outputDirectory = "Heidrun/Icons/Generated"
let maxEmojisPerChunk = 400  // keeps each chunk well under file_length: 800

guard let raw = try? String(contentsOfFile: inputPath, encoding: .utf8) else {
    fputs("Failed to read \(inputPath). Run from the repo root.\n", stderr)
    exit(1)
}

struct ParsedEmoji {
    let glyph: String
    let name: String
}

var groups: [(name: String, emojis: [ParsedEmoji])] = []
var currentGroup: String?
var unicodeVersion = "unknown"

// "Component" holds skin-tone modifiers + hair styles — meant for
// composition, not standalone avatar picks. Skip the whole group.
let skippedGroups: Set<String> = ["Component"]

for line in raw.split(separator: "\n", omittingEmptySubsequences: false) {
    let trimmed = line.trimmingCharacters(in: .whitespaces)
    if trimmed.isEmpty { continue }

    if trimmed.hasPrefix("# Version:") {
        unicodeVersion = String(trimmed.dropFirst("# Version:".count))
            .trimmingCharacters(in: .whitespaces)
        continue
    }
    if trimmed.hasPrefix("# group:") {
        let groupName = String(trimmed.dropFirst("# group:".count))
            .trimmingCharacters(in: .whitespaces)
        currentGroup = groupName
        if !skippedGroups.contains(groupName) {
            groups.append((name: groupName, emojis: []))
        }
        continue
    }
    if trimmed.hasPrefix("#") { continue }

    guard let semicolonIndex = trimmed.firstIndex(of: ";") else { continue }
    let status = trimmed[trimmed.index(after: semicolonIndex)...]
        .trimmingCharacters(in: .whitespaces)
    guard status.hasPrefix("fully-qualified") else { continue }
    guard let hashIndex = trimmed.firstIndex(of: "#") else { continue }

    let comment = trimmed[trimmed.index(after: hashIndex)...]
        .trimmingCharacters(in: .whitespaces)
    let parts = comment.split(separator: " ", maxSplits: 2, omittingEmptySubsequences: true)
    guard parts.count >= 3 else { continue }
    let glyph = String(parts[0])
    let name = String(parts[2])

    if let groupName = currentGroup, !skippedGroups.contains(groupName) {
        groups[groups.count - 1].emojis.append(
            ParsedEmoji(glyph: glyph, name: name)
        )
    }
}

func camelCaseIdentifier(_ groupName: String) -> String {
    let words = groupName
        .split(whereSeparator: { $0 == " " || $0 == "&" })
        .map { String($0) }
        .filter { !$0.isEmpty }
    guard let head = words.first else { return "unknown" }
    let tail = words.dropFirst().map { word in
        word.prefix(1).uppercased() + word.dropFirst()
    }.joined()
    return head.lowercased() + tail
}

func pascalCaseIdentifier(_ groupName: String) -> String {
    let camel = camelCaseIdentifier(groupName)
    guard let first = camel.first else { return camel }
    return first.uppercased() + camel.dropFirst()
}

func swiftEscape(_ source: String) -> String {
    var output = ""
    for character in source {
        switch character {
        case "\\":
            output += "\\\\"
        case "\"":
            output += "\\\""
        default:
            output.append(character)
        }
    }
    return output
}

let fileManager = FileManager.default
try? fileManager.createDirectory(atPath: outputDirectory, withIntermediateDirectories: true)

// Wipe stale per-group files so a future regenerate after renaming a
// group doesn't leave orphans behind.
if let existing = try? fileManager.contentsOfDirectory(atPath: outputDirectory) {
    for name in existing where name.hasSuffix(".generated.swift") {
        try? fileManager.removeItem(atPath: "\(outputDirectory)/\(name)")
    }
}

let header: [String] = [
    "// Auto-generated by Tools/GenerateEmojis.swift. Do not edit by hand.",
    "// Source: Tools/emoji-test.txt (Unicode Emoji \(unicodeVersion)).",
    "// Regenerate via:",
    "//   curl -sSL https://unicode.org/Public/emoji/latest/emoji-test.txt > Tools/emoji-test.txt",
    "//   swift Tools/GenerateEmojis.swift",
    "",
]

// Per-group extension files (chunked if oversized).
struct GroupChunks {
    let groupIdentifier: String
    let chunkProperties: [String]  // e.g. ["peopleBody1", "peopleBody2", ...]
}

var groupChunkIndex: [String: GroupChunks] = [:]

for group in groups {
    let groupIdentifier = camelCaseIdentifier(group.name)
    let groupTypeName = pascalCaseIdentifier(group.name)
    let chunkCount = max(1, (group.emojis.count + maxEmojisPerChunk - 1) / maxEmojisPerChunk)
    var chunkProperties: [String] = []

    for chunkIndex in 0..<chunkCount {
        let start = chunkIndex * maxEmojisPerChunk
        let end = min(start + maxEmojisPerChunk, group.emojis.count)
        let chunkEmojis = Array(group.emojis[start..<end])
        let propertyName = chunkCount == 1
            ? "\(groupIdentifier)Entries"
            : "\(groupIdentifier)Entries\(chunkIndex + 1)"
        chunkProperties.append(propertyName)

        var lines = header
        lines.append("import Foundation")
        lines.append("")
        lines.append("extension EmojiCatalog {")
        lines.append("    /// \(group.name) — entries \(start + 1)…\(end) of \(group.emojis.count).")
        lines.append("    static let \(propertyName): [CatalogEmoji] = [")
        for (index, emoji) in chunkEmojis.enumerated() {
            let suffix = index == chunkEmojis.count - 1 ? "" : ","
            lines.append("        CatalogEmoji(glyph: \"\(swiftEscape(emoji.glyph))\", name: \"\(swiftEscape(emoji.name))\")\(suffix)")
        }
        lines.append("    ]")
        lines.append("}")
        lines.append("")

        let suffix = chunkCount == 1 ? "" : "\(chunkIndex + 1)"
        let filePath = "\(outputDirectory)/Emojis.\(groupTypeName)\(suffix).generated.swift"
        try lines.joined(separator: "\n").write(
            toFile: filePath, atomically: true, encoding: .utf8
        )
    }

    groupChunkIndex[groupIdentifier] = GroupChunks(
        groupIdentifier: groupIdentifier,
        chunkProperties: chunkProperties
    )
}

// Main index file.
var indexLines = header
indexLines.append("import Foundation")
indexLines.append("")
indexLines.append("/// Top-level groups defined by UTS #51 (https://www.unicode.org/reports/tr51).")
indexLines.append("/// Order matches the source file, which matches Apple's Character Palette.")
indexLines.append("enum EmojiGroup: String, CaseIterable, Hashable, Sendable {")
for group in groups {
    indexLines.append("    case \(camelCaseIdentifier(group.name)) = \"\(swiftEscape(group.name))\"")
}
indexLines.append("")
indexLines.append("    /// Header text shown above each section in the picker.")
indexLines.append("    /// Identical to the raw value (CLDR English) — wrap in")
indexLines.append("    /// `LocalizedStringKey` at the call site to localize.")
indexLines.append("    var displayName: String { rawValue }")
indexLines.append("}")
indexLines.append("")
indexLines.append("/// One emoji entry: the printable glyph and the CLDR English name")
indexLines.append("/// used as the search corpus.")
indexLines.append("struct CatalogEmoji: Hashable, Sendable {")
indexLines.append("    let glyph: String")
indexLines.append("    let name: String")
indexLines.append("}")
indexLines.append("")
indexLines.append("enum EmojiCatalog {")
indexLines.append("    static let unicodeVersion: String = \"\(unicodeVersion)\"")
indexLines.append("")
indexLines.append("    /// All groups in CLDR order. Each group's entries are concatenated")
indexLines.append("    /// from per-group extension files in `Generated/`.")
indexLines.append("    static let all: [(group: EmojiGroup, emojis: [CatalogEmoji])] = [")
for (groupIndex, group) in groups.enumerated() {
    let groupIdentifier = camelCaseIdentifier(group.name)
    guard let chunks = groupChunkIndex[groupIdentifier] else { continue }
    let expression = chunks.chunkProperties.joined(separator: " + ")
    let suffix = groupIndex == groups.count - 1 ? "" : ","
    indexLines.append("        (.\(groupIdentifier), \(expression))\(suffix)")
}
indexLines.append("    ]")
indexLines.append("}")
indexLines.append("")

let indexPath = "\(outputDirectory)/Emojis.generated.swift"
try indexLines.joined(separator: "\n").write(
    toFile: indexPath, atomically: true, encoding: .utf8
)

let totalEmojis = groups.reduce(0) { $0 + $1.emojis.count }
let totalChunks = groupChunkIndex.values.reduce(0) { $0 + $1.chunkProperties.count }
print("Wrote \(totalChunks + 1) files under \(outputDirectory)/ — \(groups.count) groups, \(totalEmojis) emojis, Unicode \(unicodeVersion).")
